version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/backend
    stdin_open: true
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
volumes:
  static-vol: 
